/**
 * Sidebar navigation configuration
 * 
 * This file maintains the sidebar structure for the Adobe Commerce Storefront documentation.
 * The sidebar is organized by audience (Developers, Merchants, etc.) and uses the Starlight Sidebar Topics plugin.
 * 
 * @returns {Array} Sidebar topics configuration array
 */

/**
 * Generate sidebar configuration
 * @returns {Array} Sidebar topics array
 */
export function generateSidebar() {
  return [
    // ========= STORE FRONT DEVELOPERS =========
    {
      label: 'Developers',
      link: '/get-started/',
      icon: 'seti:json',
      items: [
        {
          label: 'Essentials',
          collapsed: false,
          items: [
            { label: 'Overview', link: '/get-started/' },
            { label: 'Learn the architecture', link: '/get-started/architecture/' },
            { label: 'Create a storefront', link: '/get-started/create-storefront' },
            { label: 'Browser compatibility', link: '/get-started/browser-compatibility/' },
            { label: 'Run Lighthouse audits', link: '/get-started/run-lighthouse/' },
            { label: "Launch checklist", link: "setup/launch/" },
          ],
        },
        {
          label: 'The Boilerplate',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/boilerplate/' },
            { label: 'Getting started', link: '/boilerplate/getting-started/' },
            { label: 'Configuration', link: '/boilerplate/configuration/' },
            { label: 'Blocks reference', link: '/boilerplate/blocks-reference/' },
            { label: 'Customizing blocks', link: '/boilerplate/customizing-blocks/' },
            { label: 'Updates', link: '/boilerplate/updates/' },
          ],
        },
        {
          label: 'Licensing',
          collapsed: true,
          autogenerate: { directory: '/licensing/' },
        },
        {
          label: 'Storefront setup',
          collapsed: true,
          items: [
            {
              label: 'Overview',
              link: '/setup/',
            },
            {
              label: 'Configuration',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/setup/configuration/' },
                { label: 'Storefront configuration', link: '/setup/configuration/commerce-configuration/' },
                { label: 'Price Book ID setup', link: '/setup/configuration/price-book-setup/' },
                { label: 'AEM Assets integration', link: '/setup/configuration/aem-assets-configuration/' },
                { label: 'AEM Commerce prerender', link: '/setup/configuration/aem-prerender/' },
                { label: 'Content delivery network', link: '/setup/configuration/content-delivery-network/' },
                { label: 'CORS setup', link: '/setup/configuration/cors-setup/' },
                { label: 'CORS troubleshooting', link: '/setup/configuration/cors-troubleshooting/' },
                { label: 'Gated content', link: '/setup/configuration/gated-content/' },
                { label: 'Data export validation', link: '/setup/discovery/data-export-validation/' },
              ],
            },
            {
              label: 'Compatibility package',
              collapsed: true,
              items: [
                { label: 'Installation', link: '/setup/configuration/storefront-compatibility/install/' },
                { label: 'Adobe Commerce 2.4.8', link: '/setup/configuration/storefront-compatibility/v248/' },
                { label: 'Adobe Commerce 2.4.7', link: '/setup/configuration/storefront-compatibility/v247/' },
                { label: 'B2B Compatibility Package', link: '/setup/configuration/storefront-compatibility-b2b/' },
              ],
            }
          ]
        },
        {
          label: 'Launch preparation',
          collapsed: true,
          items: [
            { label: 'Launch checklist', link: '/setup/launch/' },
            { label: 'Analytics instrumentation', link: '/setup/analytics/instrumentation/' },
            { label: 'Adobe Experience Platform', link: '/setup/analytics/adobe-experience-platform/' },
            { label: 'SEO indexing', link: '/setup/seo/indexing/' },
            { label: 'SEO metadata', link: '/setup/seo/metadata/' },
          ],
        },
        // ---------- HOW-TOS ----------
        {
          label: 'How-Tos',
          collapsed: true,
          items: [
            { label: 'Federated search', link: '/how-tos/federated-search/' },
            { label: 'Luma Bridge', link: '/setup/discovery/luma-bridge/' },
            { label: 'Multistore', link: '/setup/configuration/multistore-setup/' },
            {
              label: 'Cart',
              collapsed: true,
              items: [
                { label: 'Configure cart summary', link: '/dropins/cart/tutorials/configure-cart-summary/' },
                { label: 'Add custom product lines', link: '/dropins/cart/tutorials/add-product-lines-to-cart-summary/' },
                { label: 'Customize order summary lines', link: '/dropins/cart/tutorials/order-summary-lines/' },
                { label: 'Add gift options to PDP', link: '/dropins/cart/tutorials/gift-options/' },
                { label: 'Add messages to mini cart', link: '/dropins/cart/tutorials/add-messages-to-mini-cart/' },
                { label: 'Enable product variation updates', link: '/dropins/cart/tutorials/enable-product-variation-updates-in-cart/' },
              ],
            },
            {
              label: 'Checkout',
              collapsed: true,
              items: [
                { label: 'Add payment method', link: '/dropins/checkout/tutorials/add-payment-method/' },
                { label: 'Integrate address verification', link: '/dropins/checkout/tutorials/address-integration/' },
                { label: 'Validate shipping address', link: '/dropins/checkout/tutorials/validate-shipping-address/' },
                { label: 'Buy online, pickup in store', link: '/dropins/checkout/tutorials/buy-online-pickup-in-store/' },
                { label: 'Implement multi-step checkout', link: '/dropins/checkout/tutorials/multi-step/' },
              ],
            },
            {
              label: 'Order',
              collapsed: true,
              items: [
                { label: 'Enable order cancellation', link: '/dropins/order/tutorials/order-cancellation/' },
              ],
            },
            {
              label: 'User Account',
              collapsed: true,
              items: [
                { label: 'Customize layout', link: '/dropins/user-account/tutorials/customize-layout/' },
                { label: 'Validate address', link: '/dropins/user-account/tutorials/validate-address/' },
              ],
            },
          ],
        },
        // ---------- DROP-INS Overview ----------
        {
          label: 'Drop-ins',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/dropins/all/introduction/' },
            { label: 'Extend or create?', link: '/dropins/all/extend-or-create/' },
            { label: 'Using drop-ins', link: '/dropins/all/quick-start/' },
            { label: 'Commerce blocks', link: '/dropins/all/commerce-blocks/' },
            { label: 'Styling', link: '/dropins/all/styling/' },
            { label: 'Branding', link: '/dropins/all/branding/' },
            { label: 'Labeling and Localization', link: '/dropins/all/labeling/' },
            { label: 'Localizing Links', link: '/dropins/all/linking/' },
            { label: 'Dictionaries', link: '/dropins/all/dictionaries/' },
            { label: 'Slots', link: '/dropins/all/slots/' },
            { label: 'Layouts', link: '/dropins/all/layouts/' },
            { label: 'Events', link: '/dropins/all/events/' },
            { label: 'Common events', link: '/dropins/all/common-events/' },
            { label: 'Extending', link: '/dropins/all/extending/' },
            { label: 'Creating', link: '/dropins/all/creating/' },
          ],
        },

        // ---------- B2C DROP-INS ----------
        {
          label: 'B2C Drop-ins',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/dropins/' },
            {
              label: 'Cart',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/cart/' },
                { label: 'Quick Start', link: '/dropins/cart/quick-start/' },
                { label: 'Initialization', link: '/dropins/cart/initialization/' },
                { label: 'Slots', link: '/dropins/cart/slots/' },
                { label: 'Styles', link: '/dropins/cart/styles/' },
                { label: 'Functions', link: '/dropins/cart/functions/' },
                { label: 'Events', link: '/dropins/cart/events/' },
                { label: 'Dictionary', link: '/dropins/cart/dictionary/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/cart/containers/' },
                    { label: 'CartSummaryGrid', link: '/dropins/cart/containers/cart-summary-grid/' },
                    { label: 'CartSummaryList', link: '/dropins/cart/containers/cart-summary-list/' },
                    { label: 'CartSummaryTable', link: '/dropins/cart/containers/cart-summary-table/' },
                    { label: 'Coupons', link: '/dropins/cart/containers/coupons/' },
                    { label: 'EmptyCart', link: '/dropins/cart/containers/empty-cart/' },
                    { label: 'EstimateShipping', link: '/dropins/cart/containers/estimate-shipping/' },
                    { label: 'GiftCards', link: '/dropins/cart/containers/gift-cards/' },
                    { label: 'GiftOptions', link: '/dropins/cart/containers/gift-options/' },
                    { label: 'MiniCart', link: '/dropins/cart/containers/mini-cart/' },
                    { label: 'OrderSummary', link: '/dropins/cart/containers/order-summary/' },
                    { label: 'OrderSummaryLine', link: '/dropins/cart/containers/order-summary-line/' },
                  ],
                },
              ],
            },
            {
              label: 'Checkout',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/checkout/' },
                { label: 'Quick Start', link: '/dropins/checkout/quick-start/' },
                { label: 'Initialization', link: '/dropins/checkout/initialization/' },
                { label: 'Extending', link: '/dropins/checkout/extending/' },
                { label: 'Error handling', link: '/dropins/checkout/error-handling/' },
                { label: 'Event handling', link: '/dropins/checkout/event-handling/' },
                { label: 'Utility functions', link: '/dropins/checkout/utilities/' },
                { label: 'Slots', link: '/dropins/checkout/slots/' },
                { label: 'Styles', link: '/dropins/checkout/styles/' },
                { label: 'Functions', link: '/dropins/checkout/functions/' },
                { label: 'Events', link: '/dropins/checkout/events/' },
                { label: 'Dictionary', link: '/dropins/checkout/dictionary/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/checkout/containers/' },
                    { label: 'AddressValidation', link: '/dropins/checkout/containers/address-validation/' },
                    { label: 'BillToShippingAddress', link: '/dropins/checkout/containers/bill-to-shipping-address/' },
                    { label: 'EstimateShipping', link: '/dropins/checkout/containers/estimate-shipping/' },
                    { label: 'LoginForm', link: '/dropins/checkout/containers/login-form/' },
                    { label: 'MergedCartBanner', link: '/dropins/checkout/containers/merged-cart-banner/' },
                    { label: 'OutOfStock', link: '/dropins/checkout/containers/out-of-stock/' },
                    { label: 'PaymentMethods', link: '/dropins/checkout/containers/payment-methods/' },
                    { label: 'PaymentOnAccount', link: '/dropins/checkout/containers/payment-on-account/' },
                    { label: 'PlaceOrder', link: '/dropins/checkout/containers/place-order/' },
                    { label: 'PurchaseOrder', link: '/dropins/checkout/containers/purchase-order/' },
                    { label: 'ServerError', link: '/dropins/checkout/containers/server-error/' },
                    { label: 'ShippingMethods', link: '/dropins/checkout/containers/shipping-methods/' },
                    { label: 'TermsAndConditions', link: '/dropins/checkout/containers/terms-and-conditions/' },
                  ],
                },
              ],
            },
            {
              label: 'Order Management',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/order/' },
                { label: 'Quick Start', link: '/dropins/order/quick-start/' },
                { label: 'Initialization', link: '/dropins/order/initialization/' },
                { label: 'Slots', link: '/dropins/order/slots/' },
                { label: 'Styles', link: '/dropins/order/styles/' },
                { label: 'Functions', link: '/dropins/order/functions/' },
                { label: 'Events', link: '/dropins/order/events/' },
                { label: 'Dictionary', link: '/dropins/order/dictionary/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/order/containers/' },
                    { label: 'CreateReturn', link: '/dropins/order/containers/create-return/' },
                    { label: 'CustomerDetails', link: '/dropins/order/containers/customer-details/' },
                    { label: 'OrderCancelForm', link: '/dropins/order/containers/order-cancel-form/' },
                    { label: 'OrderCostSummary', link: '/dropins/order/containers/order-cost-summary/' },
                    { label: 'OrderHeader', link: '/dropins/order/containers/order-header/' },
                    { label: 'OrderProductList', link: '/dropins/order/containers/order-product-list/' },
                    { label: 'OrderReturns', link: '/dropins/order/containers/order-returns/' },
                    { label: 'OrderSearch', link: '/dropins/order/containers/order-search/' },
                    { label: 'OrderStatus', link: '/dropins/order/containers/order-status/' },
                    { label: 'ReturnsList', link: '/dropins/order/containers/returns-list/' },
                    { label: 'ShippingStatus', link: '/dropins/order/containers/shipping-status/' },
                  ],
                },
              ],
            },
            {
              label: 'Payment Services',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/payment-services/' },
                { label: 'Installation', link: '/dropins/payment-services/installation/' },
                { label: 'Initialization', link: '/dropins/payment-services/initialization/' },
                { label: 'Functions', link: '/dropins/payment-services/functions/' },
                { label: 'Events', link: '/dropins/payment-services/events/' },
                { label: 'Slots', link: '/dropins/payment-services/slots/' },
                { label: 'Styles', link: '/dropins/payment-services/styles/' },
                { label: 'Dictionary', link: '/dropins/payment-services/dictionary/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/payment-services/containers/' },
                    { label: 'ApplePay', link: '/dropins/payment-services/containers/apple-pay/' },
                    { label: 'CreditCard', link: '/dropins/payment-services/containers/credit-card/' }
                  ],
                },
              ],
            },
            {
              label: 'Personalization',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/personalization/' },
                { label: 'Quick Start', link: '/dropins/personalization/quick-start/' },
                { label: 'Initialization', link: '/dropins/personalization/initialization/' },
                { label: 'Events', link: '/dropins/personalization/events/' },
                { label: 'Dictionary', link: '/dropins/personalization/dictionary/' },
                { label: 'Functions', link: '/dropins/personalization/functions/' },
                { label: 'Slots', link: '/dropins/personalization/slots/' },
                { label: 'Styles', link: '/dropins/personalization/styles/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/personalization/containers/' },
                    { label: 'TargetedBlock', link: '/dropins/personalization/containers/targeted-block/' }
                  ],
                },
              ],
            },
            {
              label: 'Product Details Page',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/product-details/' },
                { label: 'Quick Start', link: '/dropins/product-details/quick-start/' },
                { label: 'Initialization', link: '/dropins/product-details/initialization/' },
                { label: 'Styles', link: '/dropins/product-details/styles/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/product-details/containers/' },
                    { label: 'ProductAttributes', link: '/dropins/product-details/containers/product-attributes/' },
                    { label: 'ProductDetails', link: '/dropins/product-details/containers/product-details/' },
                    { label: 'ProductDescription', link: '/dropins/product-details/containers/product-description/' },
                    { label: 'ProductGallery', link: '/dropins/product-details/containers/product-gallery/' },
                    { label: 'ProductGiftCardOptions', link: '/dropins/product-details/containers/product-gift-card-options/' },
                    { label: 'ProductGiftcardOptions', link: '/dropins/product-details/containers/product-giftcard-options/' },
                    { label: 'ProductHeader', link: '/dropins/product-details/containers/product-header/' },
                    { label: 'ProductOptions', link: '/dropins/product-details/containers/product-options/' },
                    { label: 'ProductPrice', link: '/dropins/product-details/containers/product-price/' },
                    { label: 'ProductQuantity', link: '/dropins/product-details/containers/product-quantity/' },
                    { label: 'ProductShortDescription', link: '/dropins/product-details/containers/product-short-description/' },
                  ],
                },
                { label: 'Functions', link: '/dropins/product-details/functions/' },
                { label: 'Slots', link: '/dropins/product-details/slots/' },
                { label: 'Events', link: '/dropins/product-details/events/' },
                { label: 'Dictionary', link: '/dropins/product-details/dictionary/' },
              ],
            },
            {
              label: 'Product Discovery',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/product-discovery/' },
                { label: 'Quick Start', link: '/dropins/product-discovery/quick-start/' },
                { label: 'Initialization', link: '/dropins/product-discovery/initialization/' },
                { label: 'Functions', link: '/dropins/product-discovery/functions/' },
                { label: 'Events', link: '/dropins/product-discovery/events/' },
                { label: 'Dictionary', link: '/dropins/product-discovery/dictionary/' },
                { label: 'Slots', link: '/dropins/product-discovery/slots/' },
                { label: 'Styles', link: '/dropins/product-discovery/styles/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/product-discovery/containers/' },
                    { label: 'SearchResults', link: '/dropins/product-discovery/containers/search-results/' },
                    { label: 'Facets', link: '/dropins/product-discovery/containers/facets/' },
                    { label: 'SortBy', link: '/dropins/product-discovery/containers/sort-by/' },
                    { label: 'Pagination', link: '/dropins/product-discovery/containers/pagination/' },
                  ],
                },
              ],
            },
            {
              label: 'Recommendations',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/recommendations/' },
                { label: 'Quick Start', link: '/dropins/recommendations/quick-start/' },
                { label: 'Initialization', link: '/dropins/recommendations/initialization/' },
                { label: 'Functions', link: '/dropins/recommendations/functions/' },
                { label: 'Events', link: '/dropins/recommendations/events/' },
                { label: 'Dictionary', link: '/dropins/recommendations/dictionary/' },
                { label: 'Slots', link: '/dropins/recommendations/slots/' },
                { label: 'Styles', link: '/dropins/recommendations/styles/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/recommendations/containers/' },
                    { label: 'ProductList', link: '/dropins/recommendations/containers/product-list/' }
                  ],
                },
              ],
            },
            {
              label: 'User Account',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/user-account/' },
                { label: 'Quick Start', link: '/dropins/user-account/quick-start/' },
                { label: 'Initialization', link: '/dropins/user-account/initialization/' },
                { label: 'Functions', link: '/dropins/user-account/functions/' },
                { label: 'Slots', link: '/dropins/user-account/slots/' },
                { label: 'Styles', link: '/dropins/user-account/styles/' },
                { label: 'Events', link: '/dropins/user-account/events/' },
                { label: 'Dictionary', link: '/dropins/user-account/dictionary/' },
                { label: 'Sidebar', link: '/dropins/user-account/sidebar/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/user-account/containers/' },
                    { label: 'Addresses', link: '/dropins/user-account/containers/addresses/' },
                    { label: 'AddressForm', link: '/dropins/user-account/containers/address-form/' },
                    { label: 'AddressValidation', link: '/dropins/user-account/containers/address-validation/' },
                    { label: 'CustomerInformation', link: '/dropins/user-account/containers/customer-information/' },
                    { label: 'OrdersList', link: '/dropins/user-account/containers/orders-list/' },
                  ],
                },
              ],
            },
            {
              label: 'User Authentication',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/user-auth/' },
                { label: 'Quick Start', link: '/dropins/user-auth/quick-start/' },
                { label: 'Initialization', link: '/dropins/user-auth/initialization/' },
                { label: 'reCAPTCHA', link: '/dropins/user-auth/recaptcha/' },
                { label: 'Slots', link: '/dropins/user-auth/slots/' },
                { label: 'Styles', link: '/dropins/user-auth/styles/' },
                { label: 'Events', link: '/dropins/user-auth/events/' },
                { label: 'Functions', link: '/dropins/user-auth/functions/' },
                { label: 'Dictionary', link: '/dropins/user-auth/dictionary/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/user-auth/containers/' },
                    { label: 'AuthCombine', link: '/dropins/user-auth/containers/auth-combine/' },
                    { label: 'ResetPassword', link: '/dropins/user-auth/containers/reset-password/' },
                    { label: 'SignIn', link: '/dropins/user-auth/containers/sign-in/' },
                    { label: 'SignUp', link: '/dropins/user-auth/containers/sign-up/' },
                    { label: 'SuccessNotification', link: '/dropins/user-auth/containers/success-notification/' },
                    { label: 'UpdatePassword', link: '/dropins/user-auth/containers/update-password/' },
                  ],
                },
              ],
            },
            {
              label: 'Wishlist',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins/wishlist/' },
                { label: 'Quick Start', link: '/dropins/wishlist/quick-start/' },
                { label: 'Initialization', link: '/dropins/wishlist/initialization/' },
                { label: 'Functions', link: '/dropins/wishlist/functions/' },
                { label: 'Slots', link: '/dropins/wishlist/slots/' },
                { label: 'Styles', link: '/dropins/wishlist/styles/' },
                { label: 'Events', link: '/dropins/wishlist/events/' },
                { label: 'Dictionary', link: '/dropins/wishlist/dictionary/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins/wishlist/containers/' },
                    { label: 'Wishlist Container', link: '/dropins/wishlist/containers/wishlist/' },
                    { label: 'WishlistAlert', link: '/dropins/wishlist/containers/wishlist-alert/' },
                    { label: 'WishlistItem', link: '/dropins/wishlist/containers/wishlist-item/' },
                    { label: 'WishlistToggle', link: '/dropins/wishlist/containers/wishlist-toggle/' },
                  ],
                },
              ],
            },
          ],
        },

        // ---------- B2B DROP-INS ----------
        {
          label: 'B2B Drop-ins',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/dropins-b2b/' },
            {
              label: 'Company Management',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins-b2b/company-management/' },
                { label: 'Quick start', link: '/dropins-b2b/company-management/quick-start/' },
                { label: 'Functions', link: '/dropins-b2b/company-management/functions/' },
                { label: 'Events', link: '/dropins-b2b/company-management/events/' },
                { label: 'Initialization', link: '/dropins-b2b/company-management/initialization/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins-b2b/company-management/containers/' },
                    { label: 'AcceptInvitation', link: '/dropins-b2b/company-management/containers/accept-invitation/' },
                    { label: 'CompanyCredit', link: '/dropins-b2b/company-management/containers/company-credit/' },
                    { label: 'CompanyProfile', link: '/dropins-b2b/company-management/containers/company-profile/' },
                    { label: 'CompanyRegistration', link: '/dropins-b2b/company-management/containers/company-registration/' },
                    { label: 'CompanyStructure', link: '/dropins-b2b/company-management/containers/company-structure/' },
                    { label: 'CompanyUsers', link: '/dropins-b2b/company-management/containers/company-users/' },
                    { label: 'CustomerCompanyInfo', link: '/dropins-b2b/company-management/containers/customer-company-info/' },
                    { label: 'RolesAndPermissions', link: '/dropins-b2b/company-management/containers/roles-and-permissions/' },
                  ],
                },
                { label: 'Slots', link: '/dropins-b2b/company-management/slots/' },
                { label: 'Styles', link: '/dropins-b2b/company-management/styles/' },
                { label: 'Dictionary', link: '/dropins-b2b/company-management/dictionary/' },
              ],
            },
            {
              label: 'Company Switcher',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins-b2b/company-switcher/' },
                { label: 'Quick start', link: '/dropins-b2b/company-switcher/quick-start/' },
                { label: 'Functions', link: '/dropins-b2b/company-switcher/functions/' },
                { label: 'Events', link: '/dropins-b2b/company-switcher/events/' },
                { label: 'Initialization', link: '/dropins-b2b/company-switcher/initialization/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins-b2b/company-switcher/containers/' },
                    { label: 'CompanySwitcher', link: '/dropins-b2b/company-switcher/containers/company-switcher/' },
                  ],
                },
                { label: 'Slots', link: '/dropins-b2b/company-switcher/slots/' },
                { label: 'Styles', link: '/dropins-b2b/company-switcher/styles/' },
                { label: 'Dictionary', link: '/dropins-b2b/company-switcher/dictionary/' },
              ],
            },
            {
              label: 'Purchase Order',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins-b2b/purchase-order/' },
                { label: 'Quick start', link: '/dropins-b2b/purchase-order/quick-start/' },
                { label: 'Functions', link: '/dropins-b2b/purchase-order/functions/' },
                { label: 'Events', link: '/dropins-b2b/purchase-order/events/' },
                { label: 'Initialization', link: '/dropins-b2b/purchase-order/initialization/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins-b2b/purchase-order/containers/' },
                    { label: 'ApprovalRuleDetails', link: '/dropins-b2b/purchase-order/containers/approval-rule-details/' },
                    { label: 'ApprovalRuleForm', link: '/dropins-b2b/purchase-order/containers/approval-rule-form/' },
                    { label: 'ApprovalRulesList', link: '/dropins-b2b/purchase-order/containers/approval-rules-list/' },
                    { label: 'CompanyPurchaseOrders', link: '/dropins-b2b/purchase-order/containers/company-purchase-orders/' },
                    { label: 'CustomerPurchaseOrders', link: '/dropins-b2b/purchase-order/containers/customer-purchase-orders/' },
                    { label: 'PurchaseOrderApprovalFlow', link: '/dropins-b2b/purchase-order/containers/purchase-order-approval-flow/' },
                    { label: 'PurchaseOrderCommentForm', link: '/dropins-b2b/purchase-order/containers/purchase-order-comment-form/' },
                    { label: 'PurchaseOrderCommentsList', link: '/dropins-b2b/purchase-order/containers/purchase-order-comments-list/' },
                    { label: 'PurchaseOrderConfirmation', link: '/dropins-b2b/purchase-order/containers/purchase-order-confirmation/' },
                    { label: 'PurchaseOrderHistoryLog', link: '/dropins-b2b/purchase-order/containers/purchase-order-history-log/' },
                    { label: 'PurchaseOrderStatus', link: '/dropins-b2b/purchase-order/containers/purchase-order-status/' },
                    { label: 'RequireApprovalPurchaseOrders', link: '/dropins-b2b/purchase-order/containers/require-approval-purchase-orders/' },
                  ],
                },
                { label: 'Slots', link: '/dropins-b2b/purchase-order/slots/' },
                { label: 'Styles', link: '/dropins-b2b/purchase-order/styles/' },
                { label: 'Dictionary', link: '/dropins-b2b/purchase-order/dictionary/' },
              ],
            },
            {
              label: 'Quote Management',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins-b2b/quote-management/' },
                { label: 'Quick start', link: '/dropins-b2b/quote-management/quick-start/' },
                { label: 'Functions', link: '/dropins-b2b/quote-management/functions/' },
                { label: 'Events', link: '/dropins-b2b/quote-management/events/' },
                { label: 'Initialization', link: '/dropins-b2b/quote-management/initialization/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins-b2b/quote-management/containers/' },
                    { label: 'ItemsQuoted', link: '/dropins-b2b/quote-management/containers/items-quoted/' },
                    { label: 'ItemsQuotedTemplate', link: '/dropins-b2b/quote-management/containers/items-quoted-template/' },
                    { label: 'ManageNegotiableQuote', link: '/dropins-b2b/quote-management/containers/manage-negotiable-quote/' },
                    { label: 'ManageNegotiableQuoteTemplate', link: '/dropins-b2b/quote-management/containers/manage-negotiable-quote-template/' },
                    { label: 'OrderSummary', link: '/dropins-b2b/quote-management/containers/order-summary/' },
                    { label: 'OrderSummaryLine', link: '/dropins-b2b/quote-management/containers/order-summary-line/' },
                    { label: 'QuoteCommentsList', link: '/dropins-b2b/quote-management/containers/quote-comments-list/' },
                    { label: 'QuoteHistoryLog', link: '/dropins-b2b/quote-management/containers/quote-history-log/' },
                    { label: 'QuoteSummaryList', link: '/dropins-b2b/quote-management/containers/quote-summary-list/' },
                    { label: 'QuoteTemplateCommentsList', link: '/dropins-b2b/quote-management/containers/quote-template-comments-list/' },
                    { label: 'QuoteTemplateHistoryLog', link: '/dropins-b2b/quote-management/containers/quote-template-history-log/' },
                    { label: 'QuoteTemplatesListTable', link: '/dropins-b2b/quote-management/containers/quote-templates-list-table/' },
                    { label: 'QuotesListTable', link: '/dropins-b2b/quote-management/containers/quotes-list-table/' },
                    { label: 'RequestNegotiableQuoteForm', link: '/dropins-b2b/quote-management/containers/request-negotiable-quote-form/' },
                    { label: 'ShippingAddressDisplay', link: '/dropins-b2b/quote-management/containers/shipping-address-display/' },
                  ],
                },
                { label: 'Slots', link: '/dropins-b2b/quote-management/slots/' },
                { label: 'Styles', link: '/dropins-b2b/quote-management/styles/' },
                { label: 'Dictionary', link: '/dropins-b2b/quote-management/dictionary/' },
              ],
            },
            {
              label: 'Requisition List',
              collapsed: true,
              items: [
                { label: 'Overview', link: '/dropins-b2b/requisition-list/' },
                { label: 'Quick start', link: '/dropins-b2b/requisition-list/quick-start/' },
                { label: 'Functions', link: '/dropins-b2b/requisition-list/functions/' },
                { label: 'Events', link: '/dropins-b2b/requisition-list/events/' },
                { label: 'Initialization', link: '/dropins-b2b/requisition-list/initialization/' },
                {
                  label: 'Containers',
                  collapsed: false,
                  items: [
                    { label: 'Overview', link: '/dropins-b2b/requisition-list/containers/' },
                    { label: 'RequisitionListForm', link: '/dropins-b2b/requisition-list/containers/requisition-list-form/' },
                    { label: 'RequisitionListGrid', link: '/dropins-b2b/requisition-list/containers/requisition-list-grid/' },
                    { label: 'RequisitionListHeader', link: '/dropins-b2b/requisition-list/containers/requisition-list-header/' },
                    { label: 'RequisitionListSelector', link: '/dropins-b2b/requisition-list/containers/requisition-list-selector/' },
                    { label: 'RequisitionListView', link: '/dropins-b2b/requisition-list/containers/requisition-list-view/' },
                  ],
                },
                { label: 'Slots', link: '/dropins-b2b/requisition-list/slots/' },
                { label: 'Styles', link: '/dropins-b2b/requisition-list/styles/' },
                { label: 'Dictionary', link: '/dropins-b2b/requisition-list/dictionary/' },
              ],
            },
          ],
        },

        // ---------- DROP-INS SDK ----------
        {
          label: 'Drop-ins SDK',
          collapsed: true,
          items: [
            { label: 'SDK introduction', link: '/sdk/' },
            { label: 'SDK CLI usage', link: '/sdk/get-started/cli/' },
            {
              label: 'SDK components',
              collapsed: true,
              items: [
                { label: 'Components overview', link: '/sdk/components/overview/' },
                { label: 'Accordion', link: '/sdk/components/accordion/' },
                { label: 'ActionButton', link: '/sdk/components/actionbutton/' },
                { label: 'ActionButtonGroup', link: '/sdk/components/actionbuttongroup/' },
                { label: 'AlertBanner', link: '/sdk/components/alertbanner/' },
                { label: 'Breadcrumbs', link: '/sdk/components/breadcrumbs/' },
                { label: 'Button', link: '/sdk/components/button/' },
                { label: 'Card', link: '/sdk/components/card/' },
                { label: 'CartItem', link: '/sdk/components/cartitem/' },
                { label: 'CartList', link: '/sdk/components/cartlist/' },
                { label: 'Checkbox', link: '/sdk/components/checkbox/' },
                { label: 'ColorSwatch', link: '/sdk/components/colorswatch/' },
                { label: 'ContentGrid', link: '/sdk/components/contentgrid/' },
                { label: 'Divider', link: '/sdk/components/divider/' },
                { label: 'Field', link: '/sdk/components/field/' },
                { label: 'Header', link: '/sdk/components/header/' },
                { label: 'Icon', link: '/sdk/components/icon/' },
                { label: 'IllustratedMessage', link: '/sdk/components/illustratedmessage/' },
                { label: 'Image', link: '/sdk/components/image/' },
                { label: 'ImageSwatch', link: '/sdk/components/imageswatch/' },
                { label: 'Incrementer', link: '/sdk/components/incrementer/' },
                { label: 'InlineAlert', link: '/sdk/components/inlinealert/' },
                { label: 'Input', link: '/sdk/components/input/' },
                { label: 'InputDate', link: '/sdk/components/inputdate/' },
                { label: 'InputFile', link: '/sdk/components/inputfile/' },
                { label: 'InputPassword', link: '/sdk/components/inputpassword/' },
                { label: 'Modal', link: '/sdk/components/modal/' },
                { label: 'Pagination', link: '/sdk/components/pagination/' },
                { label: 'Picker', link: '/sdk/components/picker/' },
                { label: 'Portal', link: '/sdk/components/portal/' },
                { label: 'Price', link: '/sdk/components/price/' },
                { label: 'PriceRange', link: '/sdk/components/pricerange/' },
                { label: 'ProductItemCard', link: '/sdk/components/productitemcard/' },
                { label: 'ProgressSpinner', link: '/sdk/components/progressspinner/' },
                { label: 'RadioButton', link: '/sdk/components/radiobutton/' },
                { label: 'Skeleton', link: '/sdk/components/skeleton/' },
                { label: 'Tag', link: '/sdk/components/tag/' },
                { label: 'TextArea', link: '/sdk/components/textarea/' },
                { label: 'TextSwatch', link: '/sdk/components/textswatch/' },
                { label: 'ToggleButton', link: '/sdk/components/togglebutton/' },
              ],
            },
            {
              label: 'SDK design',
              collapsed: true,
              items: [
                { label: 'Design overview', link: '/sdk/design/' },
                { label: 'Design tokens', link: '/sdk/design/base/' },
                { label: 'Colors', link: '/sdk/design/colors/' },
                { label: 'Typography', link: '/sdk/design/typography/' },
                { label: 'Spacing', link: '/sdk/design/spacing/' },
                { label: 'Shapes', link: '/sdk/design/shapes/' },
                { label: 'Grid', link: '/sdk/design/grid/' },
              ],
            },
            {
              label: 'SDK reference',
              collapsed: true,
              items: [
                { label: 'Reference overview', link: '/sdk/reference/' },
                { label: 'Events', link: '/sdk/reference/events/' },
                { label: 'GraphQL', link: '/sdk/reference/graphql/' },
                { label: 'Initializer', link: '/sdk/reference/initializer/' },
                { label: 'Links', link: '/sdk/reference/links/' },
                { label: 'Render', link: '/sdk/reference/render/' },
                { label: 'reCAPTCHA', link: '/sdk/reference/recaptcha/' },
                { label: 'Slots', link: '/sdk/reference/slots/' },
                { label: 'VComponent', link: '/sdk/reference/vcomponent/' },
              ],
            },
            {
              label: 'SDK utilities',
              collapsed: true,
              items: [
                { label: 'Utilities overview', link: '/sdk/utilities/' },
                { label: 'classList', link: '/sdk/utilities/classlist/' },
                { label: 'debounce', link: '/sdk/utilities/debounce/' },
                { label: 'deepmerge', link: '/sdk/utilities/deepmerge/' },
                { label: 'getCookie', link: '/sdk/utilities/getcookie/' },
                { label: 'getFormErrors', link: '/sdk/utilities/getformerrors/' },
                { label: 'getFormValues', link: '/sdk/utilities/getformvalues/' },
                { label: 'getPathValue', link: '/sdk/utilities/getpathvalue/' },
              ],
            },
          ],
        },

        // ---------- OTHER ----------
        {
          label: 'Troubleshooting',
          collapsed: true,
          autogenerate: { directory: '/troubleshooting/' },
        },
        {
          label: 'Resources',
          collapsed: true,
          autogenerate: { directory: '/resources/' },
        },
      ],
    },

    // ========= MERCHANTS =========
    {
      label: 'Merchants',
      link: '/merchants/quick-start/',
      icon: 'seti:svg',
      items: [
        {
          label: 'Quick start',
          items: [
            { label: 'Overview', link: '/merchants/quick-start/' },
            { label: 'What is Commerce Storefront?', link: '/merchants/quick-start/create-content/' },
            { label: 'Your first page', link: '/merchants/quick-start/your-first-page/' },
            { label: 'Using the Document Authoring tool', link: '/merchants/quick-start/document-authoring/' },
            { label: 'Using the Visual Editor', link: '/merchants/quick-start/visual-editor/' },
            // { label: 'Using digital assets management', link: '/merchants/quick-start/digital-assets-management/' },
            { label: 'Using Content and Commerce blocks', link: '/merchants/quick-start/content-commerce-blocks/' },
            { label: 'Page metadata', link: '/merchants/quick-start/page-metadata/' },
            { label: 'Section metadata', link: '/merchants/quick-start/section-metadata/' },
            {
              label: 'Localization',
              collapsed: true,
              items: [
                { label: 'Document Authoring workflow', link: '/merchants/quick-start/content-localization/' },
                { label: 'Universal Editor workflow', link: '/merchants/quick-start/content-localization-universal-editor/' },
                { label: 'Commerce-specific tasks', link: '/merchants/quick-start/content-localization-commerce-tasks/' },
              ],
            },
          ],
        },
        {
          label: 'Commerce blocks',
          items: [
            { label: 'Overview', link: '/merchants/commerce-blocks/' },
            { label: 'Personalization', link: '/merchants/commerce-blocks/personalization/' },
            { label: 'Product recommendations', link: '/merchants/commerce-blocks/product-recommendations/' },
            { label: 'Account Header', link: '/merchants/blocks/commerce-account-header/' },
            { label: 'Account Sidebar', link: '/merchants/blocks/commerce-account-sidebar/' },
            { label: 'Addresses', link: '/merchants/blocks/commerce-addresses/' },
            { label: 'Cart', link: '/merchants/blocks/commerce-cart/' },
            { label: 'Checkout', link: '/merchants/blocks/commerce-checkout/' },
            { label: 'Confirm Account', link: '/merchants/blocks/commerce-confirm-account/' },
            { label: 'Create Account', link: '/merchants/blocks/commerce-create-account/' },
            { label: 'Create Password', link: '/merchants/blocks/commerce-create-password/' },
            { label: 'Create Return', link: '/merchants/blocks/commerce-create-return/' },
            { label: 'Customer Details', link: '/merchants/blocks/commerce-customer-details/' },
            { label: 'Customer Information', link: '/merchants/blocks/commerce-customer-information/' },
            { label: 'Forgot Password', link: '/merchants/blocks/commerce-forgot-password/' },
            { label: 'Gift Options', link: '/merchants/blocks/commerce-gift-options/' },
            { label: 'Login', link: '/merchants/blocks/commerce-login/' },
            { label: 'Mini Cart', link: '/merchants/blocks/commerce-mini-cart/' },
            { label: 'Order Cost Summary', link: '/merchants/blocks/commerce-order-cost-summary/' },
            { label: 'Order Header', link: '/merchants/blocks/commerce-order-header/' },
            { label: 'Order Product List', link: '/merchants/blocks/commerce-order-product-list/' },
            { label: 'Order Returns', link: '/merchants/blocks/commerce-order-returns/' },
            { label: 'Order Status', link: '/merchants/blocks/commerce-order-status/' },
            { label: 'Orders List', link: '/merchants/blocks/commerce-orders-list/' },
            { label: 'Return Header', link: '/merchants/blocks/commerce-return-header/' },
            { label: 'Returns List', link: '/merchants/blocks/commerce-returns-list/' },
            { label: 'Search Order', link: '/merchants/blocks/commerce-search-order/' },
            { label: 'Shipping Status', link: '/merchants/blocks/commerce-shipping-status/' },
            { label: 'Wishlist', link: '/merchants/blocks/commerce-wishlist/' },
            { label: 'Product Details', link: '/merchants/blocks/product-details/' },
            { label: 'Product List Page', link: '/merchants/blocks/product-list-page/' },
            { label: 'Product Recommendations', link: '/merchants/blocks/product-recommendations/' },
          ],
        },
        // B2B Commerce blocks (30 total): commerce-b2b-* (18), commerce-company-* (7),
        // commerce-customer-company (1), plus commerce-{account-header,account-nav,account-sidebar,checkout-success} (4)
        {
          label: 'B2B Commerce blocks',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/merchants/blocks/' },
            { label: 'Account Header', link: '/merchants/blocks/commerce-account-header/' },
            { label: 'Account Nav', link: '/merchants/blocks/commerce-account-nav/' },
            { label: 'Account Sidebar', link: '/merchants/blocks/commerce-account-sidebar/' },
            { label: 'Checkout Success', link: '/merchants/blocks/commerce-checkout-success/' },
            { label: 'Company Accept Invitation', link: '/merchants/blocks/commerce-company-accept-invitation/' },
            { label: 'Company Create', link: '/merchants/blocks/commerce-company-create/' },
            { label: 'Company Credit', link: '/merchants/blocks/commerce-company-credit/' },
            { label: 'Company Profile', link: '/merchants/blocks/commerce-company-profile/' },
            { label: 'Company Roles & Permissions', link: '/merchants/blocks/commerce-company-roles-permissions/' },
            { label: 'Company Structure', link: '/merchants/blocks/commerce-company-structure/' },
            { label: 'Company Users', link: '/merchants/blocks/commerce-company-users/' },
            { label: 'Customer Company', link: '/merchants/blocks/commerce-customer-company/' },
            { label: 'Negotiable Quote', link: '/merchants/blocks/commerce-b2b-negotiable-quote/' },
            { label: 'Negotiable Quote Template', link: '/merchants/blocks/commerce-b2b-negotiable-quote-template/' },
            { label: 'PO Approval Flow', link: '/merchants/blocks/commerce-b2b-po-approval-flow/' },
            { label: 'PO Approval Rule Details', link: '/merchants/blocks/commerce-b2b-po-approval-rule-details/' },
            { label: 'PO Approval Rule Form', link: '/merchants/blocks/commerce-b2b-po-approval-rule-form/' },
            { label: 'PO Approval Rules List', link: '/merchants/blocks/commerce-b2b-po-approval-rules-list/' },
            { label: 'PO Checkout Success', link: '/merchants/blocks/commerce-b2b-po-checkout-success/' },
            { label: 'PO Comment Form', link: '/merchants/blocks/commerce-b2b-po-comment-form/' },
            { label: 'PO Comments List', link: '/merchants/blocks/commerce-b2b-po-comments-list/' },
            { label: 'PO Company Purchase Orders', link: '/merchants/blocks/commerce-b2b-po-company-purchase-orders/' },
            { label: 'PO Customer Purchase Orders', link: '/merchants/blocks/commerce-b2b-po-customer-purchase-orders/' },
            { label: 'PO Header', link: '/merchants/blocks/commerce-b2b-po-header/' },
            { label: 'PO History Log', link: '/merchants/blocks/commerce-b2b-po-history-log/' },
            { label: 'PO Require Approval', link: '/merchants/blocks/commerce-b2b-po-require-approval-purchase-orders/' },
            { label: 'PO Status', link: '/merchants/blocks/commerce-b2b-po-status/' },
            { label: 'Quote Checkout', link: '/merchants/blocks/commerce-b2b-quote-checkout/' },
            { label: 'Requisition List', link: '/merchants/blocks/commerce-b2b-requisition-list/' },
            { label: 'Requisition List View', link: '/merchants/blocks/commerce-b2b-requisition-list-view/' },
          ],
        },
        {
          label: 'Content customizations',
          items: [
            { label: 'Overview', link: '/merchants/content-customizations/' },
            { label: 'Enrichment', link: '/merchants/content-customizations/enrichment/' },
            { label: 'Experiments', link: '/merchants/content-customizations/experiments/' },
            { label: 'Prerendered product pages', link: '/merchants/content-customizations/prerendered-product-pages/' },
            { label: 'Terms and conditions', link: '/merchants/content-customizations/terms-and-conditions/' },
          ],
        },
      ],
    },

    // ========= VIDEOS =========
    {
      label: 'Videos',
      link: '/videos/',
      icon: 'seti:video',
      items: [
        {
          label: 'Storefront videos',
          items: [
            { label: 'Overview', link: '/videos/' },
            { label: 'Add custom product lines to cart summary', link: '/videos/add-product-lines-to-cart-summary/' },
            { label: 'Buy online, pickup in store', link: '/videos/buy-online-pickup-in-store/' },
            { label: 'Customize address form layout and address lookup', link: '/videos/customize-address-form-layout/' },
            { label: 'Customize cart summary', link: '/videos/customize-cart-summary/' },
            { label: 'Customize order summary lines', link: '/videos/customize-order-summary-lines/' },
            { label: 'Multi-step checkout', link: '/videos/multi-step-checkout/' },
            { label: 'Shopper experience', link: '/videos/shopper-experience/' },
          ],
        },
      ],
    },

    // ========= PLAYGROUNDS =========
    {
      label: 'Playgrounds',
      link: '/playgrounds/',
      icon: 'laptop',
      items: [
        {
          label: 'Storefront playgrounds',
          items: [
            { label: 'Introduction', link: '/playgrounds/' },
            { label: 'Commerce API Playground', link: '/playgrounds/commerce-services/' },
            { label: 'Commerce Optimizer API Playground', link: '/playgrounds/commerce-optimizer/' },
          ],
        },
      ],
    },

    // ========= RELEASES =========
    {
      label: 'Releases',
      link: '/releases/',
      icon: 'rocket',
      collapsed: true,
      items: [
        {
          label: 'Release notes',
          items: [
            { label: 'Overview', link: '/releases/' },
            { label: 'Changelog', link: '/releases/changelog/' },
          ],
        },
        {
          label: 'Hotfixes',
          items: [
            { label: 'Centralized FetchGraphQL', link: '/releases/hotfixes/centralized-fetchgraphql/' },
          ],
        },
      ],
    },
  ];
}
